/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PLUS = 5;
  /** RegularExpression Id. */
  int MINUS = 6;
  /** RegularExpression Id. */
  int TIMES = 7;
  /** RegularExpression Id. */
  int DIVIDE = 8;
  /** RegularExpression Id. */
  int NUMBER = 9;
  /** RegularExpression Id. */
  int LEFT_TAG = 10;
  /** RegularExpression Id. */
  int RIGHT_TAG = 11;
  /** RegularExpression Id. */
  int VERSION = 12;
  /** RegularExpression Id. */
  int TAG_PROLOG = 13;
  /** RegularExpression Id. */
  int ENCODING = 14;
  /** RegularExpression Id. */
  int TYPE = 15;
  /** RegularExpression Id. */
  int STANDALONE = 16;
  /** RegularExpression Id. */
  int DIGIT = 17;
  /** RegularExpression Id. */
  int LETTER = 18;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "<NUMBER>",
    "\"<\"",
    "\">\"",
    "<VERSION>",
    "\"?\"",
    "<ENCODING>",
    "\"text/css\"",
    "<STANDALONE>",
    "<DIGIT>",
    "<LETTER>",
    "\"?xml version=\"",
    "\"\\\"\"",
    "\"encoding=\"",
    "\"standalone=\"",
  };

}
